apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: guess-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: maxmelodia/guess-backend:v1
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "secretpass"
