apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m            
          env:
            - name: FLASK_APP
              value: "run.py"
            - name: FLASK_DB_TYPE
              value: "postgres"
            - name: FLASK_DB_USER
              value: "postgres"
            - name: FLASK_DB_NAME
              value: "postgres"
            - name: FLASK_DB_PASSWORD
              value: "secretpass"
            - name: FLASK_DB_HOST
              value: "postgres"
            - name: FLASK_DB_PORT
              value: "5432"



